-- MySQL Script generated by MySQL Workbench
-- Mon Sep 16 16:17:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema МагазинИнтернет
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema МагазинИнтернет
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `МагазинИнтернет` DEFAULT CHARACTER SET utf8 ;
USE `МагазинИнтернет` ;

-- -----------------------------------------------------
-- Table `МагазинИнтернет`.`Users (Пользователи)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `МагазинИнтернет`.`Users (Пользователи)` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  `created_at` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `МагазинИнтернет`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `МагазинИнтернет`.`Categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT(100) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `МагазинИнтернет`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `МагазинИнтернет`.`Products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT(100) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `category_id` INT NOT NULL,
  `Order_Items_order_item_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_Products_Categories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `МагазинИнтернет`.`Categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `МагазинИнтернет`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `МагазинИнтернет`.`Orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `order_date` TIMESTAMP(1) NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `Order_Items_order_item_id` INT NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `МагазинИнтернет`.`Order_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `МагазинИнтернет`.`Order_Items` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `fk_Order_Items_Orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_Order_Items_Products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Items_Orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `МагазинИнтернет`.`Orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Items_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `МагазинИнтернет`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `МагазинИнтернет`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `МагазинИнтернет`.`Reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `rating` INT NOT NULL,
  `comment` TEXT(100) NOT NULL,
  `created_at` TIMESTAMP(1) NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_Reviews_Products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_Reviews_Users (Пользователи)1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reviews_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `МагазинИнтернет`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reviews_Users (Пользователи)1`
    FOREIGN KEY (`user_id`)
    REFERENCES `МагазинИнтернет`.`Users (Пользователи)` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `МагазинИнтернет`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `МагазинИнтернет`.`Addresses` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL DEFAULT FOREIGN KEY,
  `street` VARCHAR(255) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `postal_code` VARCHAR(20) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `fk_Addresses_Users (Пользователи)1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_Users (Пользователи)1`
    FOREIGN KEY (`user_id`)
    REFERENCES `МагазинИнтернет`.`Users (Пользователи)` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
